# Generated by Django 4.1.1 on 2022-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_food_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='food_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='prise',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='pro_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='shop/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='waight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='main_food',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
