# Generated by Django 4.1.1 on 2022-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_food_data', '0002_shop_product_name_shop_food_title_shop_prise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='waight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
