# Generated by Django 4.1.1 on 2022-10-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_food_data', '0005_alter_shop_pro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='food_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='main_food',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
