# Generated by Django 4.1.1 on 2022-10-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_food_data', '0007_remove_shop_main_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[(0, 1), (1, 2), (2, 3)], max_length=100, null=True),
        ),
    ]
