# Generated by Django 4.1.1 on 2022-10-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_food_data', '0008_shop_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
    ]
