# Generated by Django 4.1.1 on 2022-10-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_food_data', '0009_remove_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
