# Generated by Django 4.1.1 on 2022-11-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_food_data', '0010_shop_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='quntity',
            field=models.IntegerField(default=1),
        ),
    ]
